spring:
  application:
    name: movecloud-usermanagement-service
    config:
      import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

  profiles:
    active: local

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    url: jdbc:mysql://localhost:3306/movecloud
    username: root
    password: dushyanth
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8082
  servlet:
    context-path: /user-management-service

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

api:
  base-url: http://localhost:8082/api

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/