spring:
  application:
    name: movecloud-workflow-service
    config:
      import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:mysql://localhost:3306/movecloud
    username: root
    password: dushyanth
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  main:
    web-application-type: servlet

server:
  port: 8083

movecloud:
  giturl: https://gitlab.com/veeraiahmadamanchi1/blueprints.git
  gitusername: veeraiahmadamanchi@gmail.com
  gitpassword: Nani7@1997
  gitbranch: main

api:
  base-url: http://localhost:8083

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/